# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  chronicle-cpp-consumer:
    build: .
    ports:
      - 8686:8686
    depends_on:
      - mongo
    stop_grace_period: 30m
    entrypoint: /app/entrypoint.sh

  chronicle-receiver:
    build: ./eos-chronicle
    volumes:
      - ./examples/chronicle:/build/eos-chronicle/config
    command: ["/build/eos-chronicle/build/chronicle-receiver", "--config-dir", "/build/eos-chronicle/config", "--data-dir", "/build/eos-chronicle/data"]
    depends_on:
      - chronicle-cpp-consumer
    stop_grace_period: 30m
